---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "dependabot[bot]"
    reviewers:
      - "fabasoad"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "dependabot[bot]"
    reviewers:
      - "fabasoad"
    labels:
      - "dependencies"
