---
name: Setup COBOL
author: Yevhen Fabizhevskyi
description: This action sets up GnuCOBOL.
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: "GnuCOBOL version."
    required: false
    default: "3.2"
  force:
    description: |
      If "true" it installs cobc even if it is already installed on a runner.
      Otherwise, skips installation.
    default: "false"
    required: false
outputs:
  installed:
    description: Whether cobc was installed or not.
    value: "${{ steps.install-cobc.outcome == 'success' }}"
runs:
  using: "composite"
  steps:
    - name: Fail
      if: ${{ runner.os != 'Linux' }}
      run: |
        echo "::error title=OS is not supported::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
        exit 1
      shell: sh

    - name: Validate inputs
      id: validate-inputs
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: ./validate-inputs.sh "${INPUT_FORCE}"
      shell: sh
      working-directory: ${{ github.action_path }}/src

    - name: Collect info
      id: info
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: ./collect-info.sh "${INPUT_FORCE}"
      shell: sh
      working-directory: ${{ github.action_path }}/src

    - name: Install COBOL
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      id: install-cobc
      env:
        INPUT_VERSION: "${{ inputs.version }}"
      run: ./install-cobc.sh "${INPUT_VERSION}" "${{ steps.info.outputs.bin-path }}"
      shell: sh
      working-directory: ${{ github.action_path }}/src
