---
name: Setup COBOL
author: Yevhen Fabizhevskyi
description: This action sets up GnuCOBOL.
branding:
  icon: chevrons-right
  color: gray-dark
inputs:
  version:
    description: 'GnuCOBOL version.'
    required: false
    default: '3.1.2'
runs:
  using: 'composite'
  steps:
    - name: Fail
      uses: actions/github-script@v6
      if: ${{ runner.os != 'Linux' }}
      with:
        script: core.setFailed('${{ runner.os }} ${{ runner.arch }} is not supported');
    - name: Collect info
      id: info
      if: ${{ runner.os == 'Linux' }}
      run: |
        COBOL_INSTALLED=$(if command -v cobc >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "COBOL_INSTALLED=$COBOL_INSTALLED" >> $GITHUB_OUTPUT
      shell: sh
    - name: Install COBOL
      if: ${{ runner.os == 'Linux' && steps.info.outputs.COBOL_INSTALLED == 'false' }}
#      run: src/install.sh "${{ inputs.version }}"
      run: |
        apt-get update
        apt-get -y install curl tar libncurses5-dev libgmp-dev libdb-dev
        apt-get -y autoremove
        apt-get -y install iproute2

        # download and install open-cobol for dependencies (libcob >= 4.0)
        apt-get -y install ranger autoconf build-essential
        curl -sLk https://sourceforge.net/projects/open-cobol/files/gnu-cobol/"$(echo "${{ inputs.version }}" | cut -b1- | cut -b-3)"/gnucobol-"${{ inputs.version }}".tar.gz | tar xz
        cd gnucobol-"${{ inputs.version }}" && ./configure --prefix=/usr && make && make install && ldconfig && cd /tmp/ && rm -rf ./*
        apt-get -y --purge autoremove

        chmod +x /home/cobol/cobol-unit-test/run-ut
        chmod +x /home/cobol/cobol-unit-test/compile
        chmod +x /home/cobol/cobol-unit-test/upload/ZUTZCPC

        echo "/home/cobol" >> $GITHUB_PATH
      shell: sh
