---
name: Setup COBOL
author: Yevhen Fabizhevskyi
description: This action sets up GnuCOBOL.
branding:
  icon: chevrons-right
  color: gray-dark
inputs:
  version:
    description: 'GnuCOBOL version.'
    required: false
    default: '3.1.2'
runs:
  using: 'composite'
  steps:
    - name: Fail
      uses: actions/github-script@v6
      if: ${{ runner.os != 'Linux' }}
      with:
        script: core.setFailed('${{ runner.os }} ${{ runner.arch }} is not supported');
    - name: Collect info
      id: info
      if: ${{ runner.os == 'Linux' }}
      run: |
        COBOL_INSTALLED=$(if command -v cobc >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "COBOL_INSTALLED=$COBOL_INSTALLED" >> $GITHUB_OUTPUT
      shell: sh
    - name: Install COBOL
      if: ${{ runner.os == 'Linux' && steps.info.outputs.COBOL_INSTALLED == 'false' }}
      run: src/install.sh "${{ inputs.version }}"
      shell: sh
