---
name: Setup COBOL
author: Yevhen Fabizhevskyi
description: This action sets up GnuCOBOL.
branding:
  icon: chevrons-right
  color: gray-dark
inputs:
  version:
    description: 'GnuCOBOL version.'
    required: false
    default: '3.1.2'
runs:
  using: 'node16'
  main: 'dist/index.js'
