---
name: Functional Tests

on:
  push:
    branches:
      - 'fix-122'

jobs:
  remote:
    name: Remote
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        version: ['3.1.2', '3.0-rc1', '3.1-rc1', '3.1.1']
    runs-on: ubuntu-latest
    steps:
      - name: Setup COBOL
        uses: fabasoad/setup-cobol-action@fix-122
        with:
          version: ${{ matrix.version }}
      - name: Prepare script
        run: |
          cat <<EOT >> HelloWorld.cob
          HELLO * HISTORIC EXAMPLE OF HELLO WORLD IN COBOL
              IDENTIFICATION DIVISION.
              PROGRAM-ID. HELLO.
              PROCEDURE DIVISION.
                DISPLAY "Hello World!".
                STOP RUN.
          EOT
      - name: Validate script
        run: |
          cobc -x ./HelloWorld.cob
          [[ "$(./HelloWorld)" == "Hello World!" ]] || exit 1;
